# Generated by Django 5.1.2 on 2024-10-16 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make_name', models.CharField(max_length=32, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Время')),
                ('city', models.CharField(max_length=32)),
                ('color_car', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=32, verbose_name='Страна')),
                ('mileage', models.PositiveSmallIntegerField(default=0, verbose_name='Пробег')),
                ('with_photo', models.BooleanField(default=True)),
                ('drive', models.CharField(choices=[('Задний', 'Задний'), ('Передний', 'Передний'), ('Полный привод', 'Полный привод')], max_length=16, verbose_name='Привод')),
                ('engine', models.CharField(choices=[('Бензин', 'Бензин'), ('Газ', 'Газ'), ('Дизель', 'Дизель')], max_length=16)),
                ('volume', models.FloatField(default=0.8)),
                ('exchange', models.CharField(max_length=60)),
                ('steering_wheel', models.CharField(choices=[('слева', 'слева'), ('справа', 'справа')], max_length=30)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_make', to='car_store.carmake')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='car_store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_store.car')),
                ('parent_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_store.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32, unique=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_store.carmake')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='car_store.model'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
