# Generated by Django 5.1.2 on 2024-10-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Газ', 'Газ'), ('Дизель', 'Дизель'), ('Электро', 'Электро'), ('Гибрид', 'Гибрид')], max_length=16),
        ),
    ]
