# Generated by Django 5.1.2 on 2024-10-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_store', '0002_alter_car_engine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritecar',
            old_name='movie',
            new_name='car',
        ),
    ]
