# Generated by Django 5.1.2 on 2024-10-16 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_store', '0005_alter_car_add_date_alter_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='video'),
        ),
        migrations.CreateModel(
            name='CarPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car_store.car')),
            ],
        ),
    ]
